siteTitle = "Blog by Frank Pigeon"
siteDescr = "Random Thoughts and Ramblings"
siteAuthor = "Frank Pigeon"

siteTwitterUrl = "https://twitter.com/fpigeonjr"
siteGithubUrl = "https://github.com/fpigeon"
siteEmailUrl = "frank.pigeonjr@gmail.com"
siteLinkedInUrl = "https://www.linkedin.com/in/frankpigeonjr"
siteFacebookUrl = "http://www.facebook.com/frank.pigeon"
siteInstagramUrl = "http://instagram.com/fpigeonjr"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"    