siteTitle = "Blog by Frank Pigeon"
siteDescr = "San Antonian, Web Developer, and Coffee Lover"
siteAuthor = "Frank Pigeon"

siteTwitterUrl = "https://twitter.com/fpigeonjr"
siteGithubUrl = "https://github.com/fpigeonjr"
siteEmailUrl = "mailto:frank.pigeonjr@gmail.com"
siteLinkedInUrl = "https://www.linkedin.com/in/fpigeonjr"
siteInstagramUrl = "http://instagram.com/fpigeonjr"
siteGooglePlusUrl = "https://www.google.com/+FrankPigeon"
siteFacebookUrl = "https://www.facebook.com/fpigeonjr"

googleAnalyticsId = "UA-53325305-1"

linkPrefix = "/"
